In [1]:
import pandas as pd
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
df = pd.read_excel("Python_variables.xlsx", \
                 header = 0)

In [4]:
df

      Month  nieuwe baan   CV  vacatures  uwv  werkloosheid  werkloos
0   2010-01           55  100         86   49            67        67
1   2010-02           65  100         88   56            71        54
2   2010-03           63   77         88   56            85        71
3   2010-04           58   64         81   49            59        36
4   2010-05           43   62         74   45            52        44
5   2010-06            6   63         79   52            59        53
6   2010-07           66   57         70   51            25        42
7   2010-08           73   64         81   51            22        46
8   2010-09           76   86         86   51            38        59
9   2010-10           59   82         81   50            56        54
10  2010-11           56   88         80   53            45        55
11  2010-12           65   77         63   50            42        53
12  2011-01           56   87         88   59            56        71
13  2011-02           92   87         87   57            54        53
14  2011-03           64   83         80   56            53        66
15  2011-04           62   60         76   50            58        59
16  2011-05           46   61         79   55            62        67
17  2011-06           63   57         74   50            58        57
18  2011-07           76   53         72   50            28        47
19  2011-08           59   59         81   51            25        50
20  2011-09           57   77         89   56            43        56
21  2011-10           53   80         84   55            58        70
22  2011-11           64   84         87   59            63        59
23  2011-12           55   66         74   56            52        59
24  2012-01           65   83         95   64            68        63
25  2012-02           61   97         93   63            71        67
26  2012-03           66   64         87   64            78        61
27  2012-04           45   59         84   59            68        59
28  2012-05           61   57         80   68            76        64
29  2012-06           64   55         81   62            62        58
..      ...          ...  ...        ...  ...           ...       ...
42  2013-07           52   48         78   82            50        77
43  2013-08           46   51         86   77            47        75
44  2013-09           63   72         95   79            73        88
45  2013-10           58   77         95   80            66       100
46  2013-11           66   83         93   79            70        89
47  2013-12           57   64         73   78            56        84
48  2014-01           66   86        100   92            75        90
49  2014-02           83   85         92   90            74        82
50  2014-03           78   73         85   90            78        81
51  2014-04           66   59         82   84            94        80
52  2014-05           70   55         75   81            72        70
53  2014-06           85   51         73   77            68        73
54  2014-07           85   50         69   79            32        63
55  2014-08           77   54         75   75            26        53
56  2014-09           83   69         86   87            56        68
57  2014-10           81   74         82   81            57        78
58  2014-11           85   83         77   79            53        82
59  2014-12           79   70         67   80            47        69
60  2015-01           82   85         85   86            55        73
61  2015-02           90   90         86   92            52        69
62  2015-03           87   71         79   97            62        79
63  2015-04           81   60         72   83            52        62
64  2015-05           82   55         69   81            51        58
65  2015-06          100   56         70   85            57        65
66  2015-07           82   51         69   85            22        56
67  2015-08           77   54         74   82            26        52
68  2015-09           97   75         82   89            53        65
69  2015-10           79   80         76   81            40        74
70  2015-11           94   81         70   83            45        68
71  2015-12           84   66         61   93            42        70

[72 rows x 7 columns]

In [5]:
df1 = pd.read_excel("Unemployment CBS.xlsx", \
                 header = 0)

In [6]:
df1

,Arbeidsdeelname en werkloosheid per maand,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,Onderwerpen,Werkloze beroepsbevolking,Werkloze beroepsbevolking,Werkloze beroepsbevolking
1,NaN,Onderwerpen,Werkloze beroepsbevolking,Seizoengecorrigeerd,Werkloosheidspercentage
2,NaN,Leeftijd,15 tot 75 jaar,15 tot 75 jaar,15 tot 75 jaar
3,Geslacht,Perioden,x 1000,x 1000,%
4,Totaal,2010 januari,467,444,5.4
5,Totaal,2010 februari,475,443,5.5
6,Totaal,2010 maart,470,440,5.4
7,Totaal,2010 april,442,432,5.1
8,Totaal,2010 mei,433,434,5
9,Totaal,2010 juni,427,434,4.9
10,Totaal,2010 juli,410,438,4.7
11,Totaal,2010 augustus,406,437,4.7
12,Totaal,2010 september,429,433,4.9
13,Totaal,2010 oktober,425,429,4.9
14,Totaal,2010 november,431,431,4.9
15,Totaal,2010 december,408,433,4.7
16,Totaal,2011 januari,454,430,5.2
17,Totaal,2011 februari,459,425,5.3
18,Totaal,2011 maart,441,413,5.1
19,Totaal,2011 april,420,411,4.9
20,Totaal,2011 mei,416,414,4.8
21,Totaal,2011 juni,400,409,4.6
22,Totaal,2011 juli,401,425,4.6
23,Totaal,2011 augustus,398,427,4.6
24,Totaal,2011 september,442,442,5.1
25,Totaal,2011 oktober,458,458,5.2
26,Totaal,2011 november,476,474,5.4
27,Totaal,2011 december,447,473,5.1
28,Totaal,2012 januari,511,486,5.8
29,Totaal,2012 februari,514,482,5.8
...,...,...,...,...,...
46,Totaal,2013 juli,642,666,7.2
47,Totaal,2013 augustus,637,670,7.1
48,Totaal,2013 september,675,675,7.5
49,Totaal,2013 oktober,679,680,7.6
50,Totaal,2013 november,676,677,7.6
51,Totaal,2013 december,660,687,7.4
52,Totaal,2014 januari,716,691,8.1
53,Totaal,2014 februari,730,699,8.2
54,Totaal,2014 maart,717,692,8.1
55,Totaal,2014 april,694,684,7.9
56,Totaal,2014 mei,670,672,7.5
57,Totaal,2014 juni,641,656,7.2
58,Totaal,2014 juli,626,648,7
59,Totaal,2014 augustus,604,637,6.8
60,Totaal,2014 september,630,630,7.1
61,Totaal,2014 oktober,634,632,7.1
62,Totaal,2014 november,635,635,7.1
63,Totaal,2014 december,619,643,7
64,Totaal,2015 januari,674,645,7.6
65,Totaal,2015 februari,664,633,7.5
66,Totaal,2015 maart,653,626,7.3
67,Totaal,2015 april,635,625,7.1
68,Totaal,2015 mei,614,617,6.9
69,Totaal,2015 juni,595,611,6.7
70,Totaal,2015 juli,580,603,6.5
71,Totaal,2015 augustus,570,604,6.4
72,Totaal,2015 september,608,609,6.8
73,Totaal,2015 oktober,617,616,6.9
74,Totaal,2015 november,591,596,6.6
75,Totaal,2015 december,565,588,6.4

In [7]:
df11 = df1.drop(["Arbeidsdeelname en werkloosheid per maand"], axis=1)
dfonlyper2 = df11.drop(["Unnamed: 2", "Unnamed: 3"], axis=1)
dfonlyper2.rename(columns={"Unnamed: 1": "Date"})
dfonlyper2.rename(columns={"Unnamed: 4": "Percentage"})
dfonlyper2 = dfonlyper2.drop(dfonlyper2.index[[0, 1, 2, 3]])

In [8]:
df11

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Onderwerpen,Werkloze beroepsbevolking,Werkloze beroepsbevolking,Werkloze beroepsbevolking
1,Onderwerpen,Werkloze beroepsbevolking,Seizoengecorrigeerd,Werkloosheidspercentage
2,Leeftijd,15 tot 75 jaar,15 tot 75 jaar,15 tot 75 jaar
3,Perioden,x 1000,x 1000,%
4,2010 januari,467,444,5.4
5,2010 februari,475,443,5.5
6,2010 maart,470,440,5.4
7,2010 april,442,432,5.1
8,2010 mei,433,434,5
9,2010 juni,427,434,4.9
10,2010 juli,410,438,4.7
11,2010 augustus,406,437,4.7
12,2010 september,429,433,4.9
13,2010 oktober,425,429,4.9
14,2010 november,431,431,4.9
15,2010 december,408,433,4.7
16,2011 januari,454,430,5.2
17,2011 februari,459,425,5.3
18,2011 maart,441,413,5.1
19,2011 april,420,411,4.9
20,2011 mei,416,414,4.8
21,2011 juni,400,409,4.6
22,2011 juli,401,425,4.6
23,2011 augustus,398,427,4.6
24,2011 september,442,442,5.1
25,2011 oktober,458,458,5.2
26,2011 november,476,474,5.4
27,2011 december,447,473,5.1
28,2012 januari,511,486,5.8
29,2012 februari,514,482,5.8
...,...,...,...,...
46,2013 juli,642,666,7.2
47,2013 augustus,637,670,7.1
48,2013 september,675,675,7.5
49,2013 oktober,679,680,7.6
50,2013 november,676,677,7.6
51,2013 december,660,687,7.4
52,2014 januari,716,691,8.1
53,2014 februari,730,699,8.2
54,2014 maart,717,692,8.1
55,2014 april,694,684,7.9
56,2014 mei,670,672,7.5
57,2014 juni,641,656,7.2
58,2014 juli,626,648,7
59,2014 augustus,604,637,6.8
60,2014 september,630,630,7.1
61,2014 oktober,634,632,7.1
62,2014 november,635,635,7.1
63,2014 december,619,643,7
64,2015 januari,674,645,7.6
65,2015 februari,664,633,7.5
66,2015 maart,653,626,7.3
67,2015 april,635,625,7.1
68,2015 mei,614,617,6.9
69,2015 juni,595,611,6.7
70,2015 juli,580,603,6.5
71,2015 augustus,570,604,6.4
72,2015 september,608,609,6.8
73,2015 oktober,617,616,6.9
74,2015 november,591,596,6.6
75,2015 december,565,588,6.4

In [9]:
percentage = dfonlyper2.ix[:,1]
type(percentage)

pandas.core.series.Series

In [10]:
trace = Scatter(y=percentage, mode= 'lines', name = 'lines')
py.iplot([trace], filename='plot')